version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
volumes:
  db-volume: